/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50709
Source Host           : localhost:3306
Source Database       : grainmanage

Target Server Type    : MYSQL
Target Server Version : 50709
File Encoding         : 65001

Date: 2018-03-23 19:30:14
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `bm_company`
-- ----------------------------
DROP TABLE IF EXISTS `bm_company`;
CREATE TABLE `bm_company` (
  `Id` int(11) NOT NULL AUTO_INCREMENT COMMENT '公司编号',
  `UserId` int(11) NOT NULL COMMENT '用户编号',
  `Name` varchar(60) NOT NULL DEFAULT '' COMMENT '公司名称',
  `Address` varchar(200) NOT NULL DEFAULT '' COMMENT '公司地址',
  `ImgName` varchar(60) NOT NULL DEFAULT '' COMMENT '图片名称',
  `Logo` varchar(60) NOT NULL DEFAULT '' COMMENT '缩略图',
  `CreatedAt` datetime NOT NULL COMMENT '创建时间',
  `ModifiedAt` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `uq_userid` (`UserId`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of bm_company
-- ----------------------------
INSERT INTO `bm_company` VALUES ('1', '1', '粮食收购中心', '北京市中南海', 'a081c5bccc318b3c1e41891274563af5.jpg', 'a081c5bccc318b3c1e41891274563af5.jpg', '2018-03-06 15:05:35', '2018-03-20 16:02:45');
INSERT INTO `bm_company` VALUES ('9', '2', '八集粮食收购门市', '泗阳县八集街', 'a081c5bccc318b3c1e41891274563af5.jpg', 'a081c5bccc318b3c1e41891274563af5.jpg', '2018-03-19 21:24:24', null);
INSERT INTO `bm_company` VALUES ('10', '19', '测试店铺', '测试中心', 'a081c5bccc318b3c1e41891274563af5.jpg', 'a081c5bccc318b3c1e41891274563af5.jpg', '2018-03-19 21:53:59', null);

-- ----------------------------
-- Table structure for `bm_contact`
-- ----------------------------
DROP TABLE IF EXISTS `bm_contact`;
CREATE TABLE `bm_contact` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `CompId` smallint(6) NOT NULL DEFAULT '0' COMMENT '公司编号',
  `ContactName` varchar(40) NOT NULL COMMENT '客户名称',
  `Mobile` char(11) NOT NULL DEFAULT '' COMMENT '手机',
  `Weixin` varchar(60) NOT NULL DEFAULT '' COMMENT '微信号',
  `QQ` varchar(20) NOT NULL DEFAULT '' COMMENT 'QQ',
  `Email` varchar(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `Address` varchar(100) NOT NULL DEFAULT '' COMMENT '地址',
  `ImgName` varchar(60) NOT NULL DEFAULT '' COMMENT '图片名称',
  `Remark` varchar(600) NOT NULL DEFAULT '' COMMENT '附加描述',
  `CreatedBy` int(11) NOT NULL COMMENT '创建者',
  `CreatedAt` datetime NOT NULL COMMENT '创建时间',
  `ModifiedAt` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `ContactName` (`ContactName`,`Mobile`,`CompId`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of bm_contact
-- ----------------------------
INSERT INTO `bm_contact` VALUES ('1', '1', '张海川', '15801992799', '', '914023961', 'bijinshu@163.com', '江苏省南京市雨花台区花神大道', '', '', '1', '2016-01-05 18:44:49', '2018-03-02 10:10:42');
INSERT INTO `bm_contact` VALUES ('2', '1', '李玉飞', '15801992799', '', '914023961', 'bijinshu@163.com', '江苏省南京市雨花台区软件大道119号', '', '', '1', '2016-01-05 18:44:49', '2018-01-04 20:10:47');
INSERT INTO `bm_contact` VALUES ('3', '1', '王亮亮', '15801992799', '', '914023961', 'bijinshu@163.com', '李祠堂', '', '', '1', '2016-01-05 18:44:49', '2017-07-21 17:07:42');
INSERT INTO `bm_contact` VALUES ('4', '1', '张思贤', '15801992799', '', '914023961', 'bijinshu@163.com', '六塘', '', '', '1', '2016-01-05 18:44:49', '2016-05-17 18:01:29');
INSERT INTO `bm_contact` VALUES ('5', '1', '刘江', '15801992799', '', '914023961', 'bijinshu@163.com', '泓北', '', '', '1', '2016-01-05 18:44:49', '2017-07-21 16:36:18');
INSERT INTO `bm_contact` VALUES ('6', '1', '鲍菲菲', '15801992799', '', '914023961', 'bijinshu@163.com', '大石渡', '', '', '1', '2016-01-05 18:44:49', null);
INSERT INTO `bm_contact` VALUES ('7', '1', '成杰', '15801992799', '', '914023961', 'bijinshu@163.com', '芦东', '', '', '1', '2016-01-05 18:44:49', '2017-07-21 16:59:38');
INSERT INTO `bm_contact` VALUES ('8', '1', '陈千业', '15801992799', '', '914023961', 'bijinshu@163.com', '董荡', '', '', '1', '2016-01-05 18:44:49', '2016-04-05 17:28:26');
INSERT INTO `bm_contact` VALUES ('9', '1', '齐昊', '15801992799', '', '914023961', 'bijinshu@163.com', '朱圩', '', '', '1', '2016-01-05 18:44:49', null);
INSERT INTO `bm_contact` VALUES ('10', '1', '任思', '15801992799', '', '914023961', 'bijinshu@163.com', '刘庄', '', '', '1', '2016-01-05 18:44:49', null);
INSERT INTO `bm_contact` VALUES ('11', '1', '贾亮', '15801992799', '', '914023961', 'bijinshu@163.com', '张刘', '', '', '1', '2016-01-05 18:44:49', null);
INSERT INTO `bm_contact` VALUES ('12', '1', '何远', '15801992799', '', '914023961', 'bijinshu@163.com', '育红', '', '', '1', '2016-01-05 18:44:49', null);
INSERT INTO `bm_contact` VALUES ('13', '1', '文一毫', '15801992799', '', '914023961', 'bijinshu@163.com', '河东', '', '', '1', '2016-01-05 18:44:49', null);
INSERT INTO `bm_contact` VALUES ('14', '1', '鲁云', '15801992799', '', '914023961', 'bijinshu@163.com', '桥西', '', '', '1', '2016-01-05 18:44:49', null);
INSERT INTO `bm_contact` VALUES ('15', '1', '毛强国', '15801992799', '', '914023961', 'bijinshu@163.com', '桥南', '', '', '1', '2016-01-05 18:44:49', null);
INSERT INTO `bm_contact` VALUES ('16', '1', '陈桥锋', '15801992799', '', '914023961', 'bijinshu@163.com', '合兴', '', '', '1', '2016-01-05 18:44:49', null);
INSERT INTO `bm_contact` VALUES ('17', '1', '秦汉', '15801992799', '', '914023961', 'bijinshu@163.com', '葛郑', '', '', '1', '2016-01-05 18:44:49', null);
INSERT INTO `bm_contact` VALUES ('18', '1', '李双江', '15801992799', '', '914023961', 'bijinshu@163.com', '倪荡', '', '', '1', '2016-01-05 18:44:49', null);
INSERT INTO `bm_contact` VALUES ('19', '1', '贝乐石', '15801992799', '', '914023961', 'bijinshu@163.com', '马洼', '', '', '1', '2016-01-05 18:44:49', null);
INSERT INTO `bm_contact` VALUES ('20', '1', '关楚生', '15801992799', '', '914023961', 'bijinshu@163.com', '葛荡', '', '', '1', '2016-01-05 18:44:49', null);
INSERT INTO `bm_contact` VALUES ('21', '1', '楚博雄', '15801992799', '', '914023961', 'bijinshu@163.com', '八集农科', '', '', '1', '2016-01-05 18:44:49', null);
INSERT INTO `bm_contact` VALUES ('22', '1', '张一凡', '15801992799', '', '914023961', 'bijinshu@163.com', '八集', '', '', '1', '2016-01-05 18:44:49', null);
INSERT INTO `bm_contact` VALUES ('23', '1', '刘玉生', '15801992799', '', '914023961', 'bijinshu@163.com', '桥西', '', '', '1', '2016-01-05 18:44:49', null);
INSERT INTO `bm_contact` VALUES ('24', '1', '吴雪奇', '15801992799', '', '914023961', 'bijinshu@163.com', '桥南', '', '', '1', '2016-01-05 18:44:49', null);
INSERT INTO `bm_contact` VALUES ('25', '1', '赵海', '15801992799', '', '914023961', 'bijinshu@163.com', '合兴', '', '', '1', '2016-01-05 18:44:49', null);
INSERT INTO `bm_contact` VALUES ('26', '1', '江涛', '15801992799', '', '914023961', 'bijinshu@163.com', '合兴', '', '', '1', '2016-01-05 18:44:49', null);
INSERT INTO `bm_contact` VALUES ('27', '1', '萧见浪', '15801992799', '', '914023961', 'bijinshu@163.com', '合兴', '', '', '1', '2016-01-05 18:44:49', null);
INSERT INTO `bm_contact` VALUES ('28', '1', '殷了', '15801992799', '', '914023961', 'bijinshu@163.com', '合兴', '', '', '1', '2016-01-05 18:44:49', null);
INSERT INTO `bm_contact` VALUES ('29', '1', '薛子琼', '15801992799', '', '914023961', 'bijinshu@163.com', '桥西', '', '', '1', '2016-01-05 18:44:49', null);
INSERT INTO `bm_contact` VALUES ('30', '1', '姚青', '15689547841', '', '', '', '江苏省南京市雨花台区花神大道', '', '', '2', '2018-03-18 11:20:05', null);

-- ----------------------------
-- Table structure for `bm_order`
-- ----------------------------
DROP TABLE IF EXISTS `bm_order`;
CREATE TABLE `bm_order` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `Mobile` varchar(11) NOT NULL COMMENT '手机号码',
  `Address` varchar(200) NOT NULL DEFAULT '' COMMENT '地址',
  `CompId` int(11) NOT NULL DEFAULT '0' COMMENT '店铺编号',
  `CompName` varchar(60) NOT NULL DEFAULT '' COMMENT '店铺名称',
  `TotalMoney` decimal(20,2) NOT NULL COMMENT '计算总金额',
  `ActualMoney` decimal(20,2) NOT NULL COMMENT '实际成交金额',
  `Remark` varchar(600) NOT NULL DEFAULT '' COMMENT '备注',
  `Status` smallint(6) NOT NULL DEFAULT '0' COMMENT '0:待发送 1:待接单 2:已接单 3:交易成功 4:已取消 5:拒绝接单',
  `CreatedBy` int(11) NOT NULL DEFAULT '0' COMMENT '创建者',
  `CreatedAt` datetime NOT NULL COMMENT '创建时间',
  `ModifiedAt` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of bm_order
-- ----------------------------
INSERT INTO `bm_order` VALUES ('1', '15801992799', '八集', '6', '泗阳粮食收购总代理', '832.00', '832.00', '', '3', '1', '2018-03-14 13:46:37', '2018-03-15 18:24:59');
INSERT INTO `bm_order` VALUES ('2', '15801992799', '八集', '6', '泗阳粮食收购总代理', '729.00', '729.00', '', '3', '1', '2018-03-14 15:39:08', '2018-03-15 17:37:58');
INSERT INTO `bm_order` VALUES ('3', '15801992799', '历史地看', '1', '八集粮食收购', '489.00', '0.00', '快点来', '5', '2', '2018-03-16 10:38:37', '2018-03-16 16:06:01');
INSERT INTO `bm_order` VALUES ('5', '15801992799', '胜多负少', '1', '八集粮食收购', '936.00', '832.00', '松岛枫', '3', '2', '2018-03-16 10:51:22', '2018-03-19 20:52:33');
INSERT INTO `bm_order` VALUES ('6', '15801992799', '', '1', '粮食收购中心', '4916.00', '0.00', '', '1', '2', '2018-03-22 14:22:55', null);

-- ----------------------------
-- Table structure for `bm_order_detail`
-- ----------------------------
DROP TABLE IF EXISTS `bm_order_detail`;
CREATE TABLE `bm_order_detail` (
  `Id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `OrderId` int(10) unsigned NOT NULL COMMENT '订单编号',
  `ProductId` int(11) NOT NULL COMMENT '产品编号',
  `ProductName` varchar(20) NOT NULL DEFAULT '' COMMENT '产品名称',
  `Price` decimal(20,4) NOT NULL COMMENT '价格',
  `Weight` decimal(20,2) NOT NULL COMMENT '重量',
  `TotalMoney` decimal(20,2) NOT NULL COMMENT '总价',
  `ActualPrice` decimal(20,4) NOT NULL COMMENT '实际价格',
  `ActualWeight` decimal(20,2) NOT NULL COMMENT '实际重量',
  `ActualMoney` decimal(20,2) NOT NULL COMMENT '实际金额',
  `CreatedBy` int(10) unsigned NOT NULL COMMENT '创建者',
  `CreatedAt` datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of bm_order_detail
-- ----------------------------
INSERT INTO `bm_order_detail` VALUES ('1', '1', '9', '小麦', '1.0400', '500.00', '520.00', '1.0400', '800.00', '832.00', '1', '2018-03-14 13:46:37');
INSERT INTO `bm_order_detail` VALUES ('2', '2', '23', '玉米', '1.2050', '600.00', '723.00', '1.2050', '600.00', '729.00', '1', '2018-03-14 15:39:08');
INSERT INTO `bm_order_detail` VALUES ('3', '3', '25', '花生', '2.4450', '200.00', '489.00', '0.0000', '0.00', '0.00', '2', '2018-03-16 10:38:37');
INSERT INTO `bm_order_detail` VALUES ('7', '5', '9', '小麦', '1.0400', '900.00', '936.00', '1.0400', '800.00', '832.00', '2', '2018-03-16 10:51:22');
INSERT INTO `bm_order_detail` VALUES ('8', '6', '24', '菜籽', '2.2450', '800.00', '1796.00', '0.0000', '0.00', '0.00', '2', '2018-03-22 14:22:55');
INSERT INTO `bm_order_detail` VALUES ('9', '6', '9', '小麦', '1.0400', '3000.00', '3120.00', '0.0000', '0.00', '0.00', '2', '2018-03-22 14:22:55');

-- ----------------------------
-- Table structure for `bm_product`
-- ----------------------------
DROP TABLE IF EXISTS `bm_product`;
CREATE TABLE `bm_product` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(20) NOT NULL COMMENT '产品名称',
  `CompId` int(11) NOT NULL COMMENT '店铺Id',
  `CompName` varchar(60) NOT NULL DEFAULT '' COMMENT '店铺名称',
  `Price` decimal(20,4) NOT NULL COMMENT '价格',
  `Remark` varchar(600) NOT NULL DEFAULT '' COMMENT '备注',
  `Status` smallint(6) NOT NULL DEFAULT '0' COMMENT '0：离线 1：在线',
  `Source` smallint(6) NOT NULL COMMENT '来源/归属( 0：店铺产品 1：系统产品)',
  `CreatedAt` datetime NOT NULL COMMENT '创建时间',
  `CreatedBy` int(11) NOT NULL COMMENT '创建者',
  `ModifiedAt` datetime DEFAULT NULL COMMENT '修改时间',
  `ModifiedBy` int(11) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `uq_name` (`Name`,`CompId`,`Source`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of bm_product
-- ----------------------------
INSERT INTO `bm_product` VALUES ('1', '小麦', '0', '', '1.0400', '', '1', '1', '2017-08-30 00:00:00', '1', null, null);
INSERT INTO `bm_product` VALUES ('2', '黄豆', '0', '', '1.3000', '', '1', '1', '2017-08-30 00:00:00', '1', null, null);
INSERT INTO `bm_product` VALUES ('3', '大稻', '0', '', '1.2600', '', '1', '1', '2017-08-30 00:00:00', '1', null, null);
INSERT INTO `bm_product` VALUES ('4', '燕麦', '0', '', '1.3000', '', '1', '1', '2017-08-30 00:00:00', '1', null, null);
INSERT INTO `bm_product` VALUES ('5', '玉米', '0', '', '1.2050', '', '1', '1', '2017-08-30 00:00:00', '1', null, null);
INSERT INTO `bm_product` VALUES ('6', '花生', '0', '', '2.4450', '', '1', '1', '2017-08-30 00:00:00', '1', null, null);
INSERT INTO `bm_product` VALUES ('7', '菜籽', '0', '', '2.2450', '', '1', '1', '2017-08-30 00:00:00', '1', null, null);
INSERT INTO `bm_product` VALUES ('8', '小稻', '0', '', '1.2250', '', '1', '1', '2018-02-13 15:17:04', '1', '2018-03-01 17:27:25', '1');
INSERT INTO `bm_product` VALUES ('9', '小麦', '1', '八集粮食收购', '1.0400', '', '1', '0', '2018-03-07 13:07:13', '1', '2018-03-16 15:26:32', '1');
INSERT INTO `bm_product` VALUES ('21', '大稻', '1', '八集粮食收购', '1.2600', '', '1', '0', '2018-03-07 14:47:51', '1', '2018-03-16 15:26:28', '1');
INSERT INTO `bm_product` VALUES ('22', '小稻', '1', '八集粮食收购', '1.2250', '', '1', '0', '2018-03-07 14:48:01', '1', '2018-03-16 15:26:25', '1');
INSERT INTO `bm_product` VALUES ('23', '玉米', '6', '泗阳粮食收购总代理', '1.2050', '', '1', '0', '2018-03-07 14:48:47', '1', '2018-03-16 15:29:14', '2');
INSERT INTO `bm_product` VALUES ('24', '菜籽', '1', '八集粮食收购', '2.2450', '', '1', '0', '2018-03-13 19:32:29', '1', '2018-03-16 15:26:02', '1');
INSERT INTO `bm_product` VALUES ('25', '花生', '1', '八集粮食收购', '2.4450', '', '1', '0', '2018-03-13 19:32:33', '1', '2018-03-16 15:25:54', '1');
INSERT INTO `bm_product` VALUES ('26', '玉米', '1', '八集粮食收购', '1.2050', '', '1', '0', '2018-03-13 19:32:38', '1', '2018-03-16 15:25:50', '1');
INSERT INTO `bm_product` VALUES ('27', '玉米', '9', '八集粮食收购门市', '1.2050', '', '1', '0', '2018-03-19 21:41:48', '2', null, null);
INSERT INTO `bm_product` VALUES ('28', '大稻', '9', '八集粮食收购门市', '1.2600', '', '1', '0', '2018-03-19 21:41:53', '2', null, null);
INSERT INTO `bm_product` VALUES ('29', '小麦', '9', '八集粮食收购门市', '1.0400', '', '1', '0', '2018-03-19 21:41:58', '2', null, null);
INSERT INTO `bm_product` VALUES ('30', '小稻', '10', '测试店铺', '1.2250', '', '1', '0', '2018-03-19 21:54:49', '19', null, null);
INSERT INTO `bm_product` VALUES ('31', '菜籽', '10', '测试店铺', '2.2450', '', '1', '0', '2018-03-19 21:54:54', '19', null, null);
INSERT INTO `bm_product` VALUES ('32', '燕麦', '10', '测试店铺', '1.3000', '', '1', '0', '2018-03-19 21:54:59', '19', null, null);

-- ----------------------------
-- Table structure for `bm_trade`
-- ----------------------------
DROP TABLE IF EXISTS `bm_trade`;
CREATE TABLE `bm_trade` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `CompId` int(11) NOT NULL COMMENT '店铺Id',
  `ContactId` int(11) NOT NULL COMMENT '客户Id',
  `ContactName` varchar(20) NOT NULL DEFAULT '' COMMENT '联系人名称',
  `ActualMoney` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT '总成交金额',
  `TradeType` smallint(6) NOT NULL DEFAULT '0' COMMENT '0：收购: 1：出售',
  `Remark` varchar(6000) NOT NULL DEFAULT '' COMMENT '备注说明',
  `Status` smallint(6) NOT NULL COMMENT '0：等待合并 1：合并完成',
  `CreatedBy` int(11) NOT NULL COMMENT '创建者',
  `CreatedAt` datetime NOT NULL COMMENT '创建时间',
  `ModifiedAt` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=67 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of bm_trade
-- ----------------------------
INSERT INTO `bm_trade` VALUES ('66', '1', '0', '', '2279.72', '0', '', '0', '1', '2018-03-23 18:34:03', null);

-- ----------------------------
-- Table structure for `bm_trade_detail`
-- ----------------------------
DROP TABLE IF EXISTS `bm_trade_detail`;
CREATE TABLE `bm_trade_detail` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `TradeId` int(11) NOT NULL COMMENT '交易编号',
  `ProductId` int(11) NOT NULL,
  `ProductName` varchar(20) NOT NULL DEFAULT '' COMMENT '产品名称',
  `Price` decimal(20,4) NOT NULL COMMENT '价格',
  `RoughWeight` decimal(20,2) NOT NULL COMMENT '毛重',
  `Tare` decimal(20,2) NOT NULL COMMENT '皮重',
  `ActualMoney` decimal(20,2) NOT NULL COMMENT '成交金额',
  `Remark` varchar(200) NOT NULL DEFAULT '' COMMENT '备注说明',
  `CreatedAt` datetime NOT NULL COMMENT '创建时间',
  `CreatedBy` int(11) NOT NULL COMMENT '创建人',
  `ModifiedAt` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of bm_trade_detail
-- ----------------------------
INSERT INTO `bm_trade_detail` VALUES ('1', '66', '9', '小麦', '1.0400', '900.00', '1.00', '934.96', '', '2018-03-23 18:34:19', '1', null);
INSERT INTO `bm_trade_detail` VALUES ('2', '66', '24', '菜籽', '2.2450', '600.00', '1.00', '1344.76', '', '2018-03-23 18:34:22', '1', null);

-- ----------------------------
-- Table structure for `log_action`
-- ----------------------------
DROP TABLE IF EXISTS `log_action`;
CREATE TABLE `log_action` (
  `Id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `UserId` int(11) unsigned NOT NULL COMMENT '用户Id',
  `UserName` varchar(20) NOT NULL DEFAULT '' COMMENT '用户名称',
  `Path` varchar(200) NOT NULL DEFAULT '' COMMENT '动作名称',
  `ClientIP` varchar(64) NOT NULL DEFAULT '' COMMENT '访问端IP',
  `Method` varchar(6) NOT NULL DEFAULT '' COMMENT '请求方法',
  `Status` varchar(60) NOT NULL DEFAULT '' COMMENT '状态',
  `Para` text NOT NULL COMMENT '请求参数',
  `Level` smallint(6) NOT NULL COMMENT '级别',
  `StartTime` datetime NOT NULL COMMENT '调用开始时间',
  `EndTime` datetime DEFAULT NULL COMMENT '调用结束时间',
  `TimeSpan` time DEFAULT NULL COMMENT '耗时',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=29568 DEFAULT CHARSET=utf8 COMMENT='访问日志';

-- ----------------------------
-- Records of log_action
-- ----------------------------
INSERT INTO `log_action` VALUES ('29548', '1', 'bijinshu', '/Address/Edit', '221.6.15.218', 'POST', '成功', '{\"Path\":\"/User/SignIn\",\"IsWatching\":\"true\",\"IsValid\":\"true\",\"TypeId\":\"0\",\"Remark\":\"\",\"CreatedAt\":\"2018-02-11T16:43:27\",\"ModifiedAt\":\"2018-03-20T20:16:55\"}', '100', '2018-03-22 10:11:19', '2018-03-22 10:11:19', '00:00:00');
INSERT INTO `log_action` VALUES ('29549', '1', 'bijinshu', '/Address/Edit', '221.6.15.218', 'POST', '成功', '{\"Path\":\"/User/SignIn\",\"IsWatching\":\"false\",\"IsValid\":\"true\",\"TypeId\":\"0\",\"Remark\":\"\",\"CreatedAt\":\"2018-02-11T16:43:27\",\"ModifiedAt\":\"2018-03-22T10:11:19\"}', '100', '2018-03-22 10:11:33', '2018-03-22 10:11:33', '00:00:00');
INSERT INTO `log_action` VALUES ('29550', '1', 'bijinshu', '/Address/RefreshCache', '221.6.15.218', 'POST', '成功：如果应用是分布式部署，请重复刷新多次', '', '100', '2018-03-22 10:12:11', '2018-03-22 10:12:11', '00:00:00');
INSERT INTO `log_action` VALUES ('29551', '1', 'bijinshu', '/Address/RefreshDb', '221.6.15.218', 'POST', '数据库当前有66条接口地址，本次新增0条，更新0条，失效0条', '', '100', '2018-03-22 10:12:15', '2018-03-22 10:12:15', '00:00:00');
INSERT INTO `log_action` VALUES ('29552', '3', 'bj', '/Order/New', '183.193.144.3', 'POST', '存在未填写重量的产品', '{\"CompId\":\"1\",\"CompName\":\"粮食收购中心\",\"Mobile\":\"13641520682\",\"Address\":\"泗阳县八集街八集派出所向北50米\",\"Remark\":\"\",\"Details[0][ProductId]\":\"9\",\"Details[0][ProductName]\":\"小麦\",\"Details[0][Price]\":\"1.04\",\"Details[0][Weight]\":\"\"}', '80', '2018-03-22 14:22:00', '2018-03-22 14:22:00', '00:00:00');
INSERT INTO `log_action` VALUES ('29553', '2', 'bjc', '/Order/New', '122.96.40.229', 'POST', '成功', '{\"CompId\":\"1\",\"CompName\":\"粮食收购中心\",\"Mobile\":\"15801992799\",\"Address\":\"\",\"Remark\":\"\",\"Details[0][ProductId]\":\"24\",\"Details[0][ProductName]\":\"菜籽\",\"Details[0][Price]\":\"2.245\",\"Details[0][Weight]\":\"800\",\"Details[1][ProductId]\":\"9\",\"Details[1][ProductName]\":\"小麦\",\"Details[1][Price]\":\"1.04\",\"Details[1][Weight]\":\"3000\"}', '80', '2018-03-22 14:22:55', '2018-03-22 14:22:55', '00:00:00');
INSERT INTO `log_action` VALUES ('29554', '1', 'bijinshu', '/User/SignOut', 'localhost', 'GET', '', '', '100', '2018-03-22 16:20:07', '2018-03-22 16:20:07', '00:00:00');
INSERT INTO `log_action` VALUES ('29555', '2', 'bjc', '/User/SignOut', 'localhost', 'GET', '', 'returnUrl=http://localhost:34877/company/index', '80', '2018-03-22 16:28:36', '2018-03-22 16:28:37', '00:00:00');
INSERT INTO `log_action` VALUES ('29556', '2', 'bjc', '/User/SignOut', 'localhost', 'GET', '', 'returnUrl=http://localhost:34877/company/index', '80', '2018-03-22 16:28:58', '2018-03-22 16:28:58', '00:00:00');
INSERT INTO `log_action` VALUES ('29557', '2', 'bjc', '/User/SignOut', 'localhost', 'GET', '', 'returnUrl=http://localhost:34877/company/index', '80', '2018-03-22 16:29:15', '2018-03-22 16:29:15', '00:00:00');
INSERT INTO `log_action` VALUES ('29558', '2', 'bjc', '/User/SignOut', 'localhost', 'GET', '', 'returnUrl=http://localhost:34877/Order/GetPersonalOrder', '80', '2018-03-22 16:30:42', '2018-03-22 16:30:42', '00:00:00');
INSERT INTO `log_action` VALUES ('29559', '2', 'bjc', '/User/SignOut', 'localhost', 'GET', '', 'returnUrl=http://localhost:34877/Company/Index', '80', '2018-03-22 16:38:31', '2018-03-22 16:38:32', '00:00:01');
INSERT INTO `log_action` VALUES ('29560', '2', 'bjc', '/User/SignOut', 'localhost', 'GET', '', 'returnUrl=http://localhost:34877/Company/Index', '80', '2018-03-22 16:39:03', '2018-03-22 16:39:03', '00:00:00');
INSERT INTO `log_action` VALUES ('29561', '2', 'bjc', '/User/SignOut', 'localhost', 'GET', '', 'returnUrl=http://localhost:34877/Order/GetPersonalOrder', '80', '2018-03-22 16:39:17', '2018-03-22 16:39:17', '00:00:00');
INSERT INTO `log_action` VALUES ('29562', '2', 'bjc', '/User/SignOut', 'localhost', 'GET', '', 'returnUrl=http://localhost:34877/Order/GetPersonalOrder', '80', '2018-03-22 16:45:37', '2018-03-22 16:45:37', '00:00:00');
INSERT INTO `log_action` VALUES ('29563', '2', 'bjc', '/User/SignOut', 'localhost', 'GET', '', 'returnUrl=http://localhost:34877/Order/GetPersonalOrder', '80', '2018-03-22 16:46:00', '2018-03-22 16:46:00', '00:00:00');
INSERT INTO `log_action` VALUES ('29564', '2', 'bjc', '/User/SignOut', 'localhost', 'GET', '', 'returnUrl=http://localhost:34877/Company/Index', '80', '2018-03-22 16:46:07', '2018-03-22 16:46:07', '00:00:00');
INSERT INTO `log_action` VALUES ('29565', '2', 'bjc', '/User/SignOut', 'localhost', 'GET', '', 'returnUrl=http://localhost:34877/Order/GetPersonalOrder', '80', '2018-03-22 16:46:14', '2018-03-22 16:46:14', '00:00:00');
INSERT INTO `log_action` VALUES ('29566', '2', 'bjc', '/User/SignOut', 'localhost', 'GET', '', 'returnUrl=/Order/GetPersonalOrder', '80', '2018-03-22 16:49:12', '2018-03-22 16:49:12', '00:00:00');
INSERT INTO `log_action` VALUES ('29567', '2', 'bjc', '/User/SignOut', 'localhost', 'GET', '', '', '80', '2018-03-22 16:56:19', '2018-03-22 16:56:20', '00:00:01');

-- ----------------------------
-- Table structure for `log_exception`
-- ----------------------------
DROP TABLE IF EXISTS `log_exception`;
CREATE TABLE `log_exception` (
  `Id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `Path` varchar(200) NOT NULL DEFAULT '' COMMENT '调用路径',
  `Para` text NOT NULL COMMENT '请求参数',
  `Message` varchar(600) NOT NULL DEFAULT '' COMMENT '描述',
  `StackTrace` text COMMENT '堆栈信息',
  `ClientIP` varchar(64) NOT NULL DEFAULT '' COMMENT '客户端调用IP',
  `CreatedAt` datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=115 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of log_exception
-- ----------------------------
INSERT INTO `log_exception` VALUES ('36', '/User/Register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '153.3.43.174', '2018-03-17 20:05:39');
INSERT INTO `log_exception` VALUES ('37', '/User/Register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '153.3.43.174', '2018-03-17 20:31:56');
INSERT INTO `log_exception` VALUES ('38', '/User/Register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '153.3.43.174', '2018-03-17 20:32:11');
INSERT INTO `log_exception` VALUES ('39', '/User/Register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '153.3.43.174', '2018-03-18 09:21:01');
INSERT INTO `log_exception` VALUES ('40', '/User/Register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '153.3.43.174', '2018-03-18 09:21:25');
INSERT INTO `log_exception` VALUES ('41', '/User/ResetPwd', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '153.3.43.174', '2018-03-18 09:52:43');
INSERT INTO `log_exception` VALUES ('42', '/User/ResetPwd', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '153.3.43.174', '2018-03-18 09:53:03');
INSERT INTO `log_exception` VALUES ('43', '/Company/Edit', '{\"Id\":\"1\",\"Name\":\"八集粮食收购\",\"Address\":\"八集街\"}', 'Could not find a part of the path \'/images/company/fafa5efeaf3cbe3b23b2748d13e629a1.jpg\'.\n', '   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)\n   at GrainManage.Web.Controllers.CompanyController.Edit(CompanyDto input, IFormFile imgFile) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Controllers\\CompanyController.cs:line 139\n   at lambda_method(Closure , Object , Object[] )\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '112.80.124.139', '2018-03-18 13:46:56');
INSERT INTO `log_exception` VALUES ('44', '/User/SignIn', '{\"UserName\":\"bijinshu\",\"Pwd\":\"9e18b4d4b076dde35f1bcc0d8c735f067efca492\"}', 'It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING\n', '   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in c:\\code\\StackExchange.Redis\\StackExchange.Redis\\StackExchange\\Redis\\ConnectionMultiplexer.cs:line 890\n   at GrainManage.Web.Cache.RedisCache.get_Redis() in D:\\github.netcore.GrainManage\\GrainManage.Web\\Cache\\RedisCache.cs:line 124\n   at GrainManage.Web.Cache.RedisCache.Set[T](String key, T value, Nullable`1 expiresAt) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Cache\\RedisCache.cs:line 26\n   at GrainManage.Web.Controllers.UserController.SignIn(InputSignIn input, String returnUrl) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Controllers\\UserController.cs:line 71\n   at lambda_method(Closure , Object , Object[] )\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '221.6.15.218', '2018-03-19 14:50:10');
INSERT INTO `log_exception` VALUES ('45', '/User/SignIn', '{\"UserName\":\"bijinshu\",\"Pwd\":\"9e18b4d4b076dde35f1bcc0d8c735f067efca492\"}', 'It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING\n', '   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in c:\\code\\StackExchange.Redis\\StackExchange.Redis\\StackExchange\\Redis\\ConnectionMultiplexer.cs:line 890\n   at GrainManage.Web.Cache.RedisCache.get_Redis() in D:\\github.netcore.GrainManage\\GrainManage.Web\\Cache\\RedisCache.cs:line 124\n   at GrainManage.Web.Cache.RedisCache.Set[T](String key, T value, Nullable`1 expiresAt) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Cache\\RedisCache.cs:line 26\n   at GrainManage.Web.Controllers.UserController.SignIn(InputSignIn input, String returnUrl) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Controllers\\UserController.cs:line 71\n   at lambda_method(Closure , Object , Object[] )\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '221.6.15.218', '2018-03-19 14:50:29');
INSERT INTO `log_exception` VALUES ('46', '/User/SignIn', '{\"UserName\":\"bijinshu\",\"Pwd\":\"9e18b4d4b076dde35f1bcc0d8c735f067efca492\"}', 'It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING\n', '   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in c:\\code\\StackExchange.Redis\\StackExchange.Redis\\StackExchange\\Redis\\ConnectionMultiplexer.cs:line 890\n   at GrainManage.Web.Cache.RedisCache.get_Redis() in D:\\github.netcore.GrainManage\\GrainManage.Web\\Cache\\RedisCache.cs:line 124\n   at GrainManage.Web.Cache.RedisCache.Set[T](String key, T value, Nullable`1 expiresAt) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Cache\\RedisCache.cs:line 26\n   at GrainManage.Web.Controllers.UserController.SignIn(InputSignIn input, String returnUrl) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Controllers\\UserController.cs:line 71\n   at lambda_method(Closure , Object , Object[] )\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-19 14:51:23');
INSERT INTO `log_exception` VALUES ('47', '/User/SignIn', '{\"UserName\":\"bijinshu\",\"Pwd\":\"9e18b4d4b076dde35f1bcc0d8c735f067efca492\"}', 'It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING\n', '   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in c:\\code\\StackExchange.Redis\\StackExchange.Redis\\StackExchange\\Redis\\ConnectionMultiplexer.cs:line 890\n   at GrainManage.Web.Cache.RedisCache.get_Redis() in D:\\github.netcore.GrainManage\\GrainManage.Web\\Cache\\RedisCache.cs:line 124\n   at GrainManage.Web.Cache.RedisCache.Set[T](String key, T value, Nullable`1 expiresAt) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Cache\\RedisCache.cs:line 26\n   at GrainManage.Web.Controllers.UserController.SignIn(InputSignIn input, String returnUrl) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Controllers\\UserController.cs:line 71\n   at lambda_method(Closure , Object , Object[] )\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-19 14:56:38');
INSERT INTO `log_exception` VALUES ('48', '/User/ResetPwd', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '221.6.15.218', '2018-03-19 17:29:27');
INSERT INTO `log_exception` VALUES ('49', '/User/ResetPwd', 'nsukey=eXhRydxRCt+WpFxx07MKzE0wcVoHvLzPfHkM+dsKsyAGrRbmlW/HRot85zajl5V9A/ypA2newckfQ/xLHnIBouBenxYNWA0U+le+ZXoFz0sJ8IkB0fvVgc7lcXI2WZ4bhVTyN8A82CBCq6QlS3MnrUD2hPZnRY36RDxarFHcVu3CMHlY1ItiiLjMfN6KHhl2LtNU6Q2MyufLxJEFIrxyiA==', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '61.151.180.39', '2018-03-19 17:29:28');
INSERT INTO `log_exception` VALUES ('50', '/User/ResetPwd', 'nsukey=eXhRydxRCt+WpFxx07MKzE0wcVoHvLzPfHkM+dsKsyAGrRbmlW/HRot85zajl5V9A/ypA2newckfQ/xLHnIBouBenxYNWA0U+le+ZXoFz0sJ8IkB0fvVgc7lcXI2WZ4bhVTyN8A82CBCq6QlS3MnrUD2hPZnRY36RDxarFHcVu3CMHlY1ItiiLjMfN6KHhl2LtNU6Q2MyufLxJEFIrxyiA==', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '221.6.15.218', '2018-03-19 17:29:28');
INSERT INTO `log_exception` VALUES ('51', '/User/Register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '221.6.15.218', '2018-03-19 17:29:33');
INSERT INTO `log_exception` VALUES ('52', '/User/Register', 'nsukey=KJv2964lM1m3zc5np4x3VbzIgt7+Z87yO2G/MIOI4n40xw0m7K720JTd8wG1wxWdVlzkPraKGqdXivUNjHLoDHl+fX3w51LG72MviRS1rs/pqw40zTPyD3Gfnzl/ioDaqbeCN67/RIadXz3z4dmIRDIUVEw4RhN80XZgp41+B7t6N0WHWASyWzVOIStWVgR5XKs40O72bJMsZUz5z2DOrw==', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '58.247.212.98', '2018-03-19 17:29:35');
INSERT INTO `log_exception` VALUES ('53', '/User/Register', 'nsukey=KJv2964lM1m3zc5np4x3VbzIgt7+Z87yO2G/MIOI4n40xw0m7K720JTd8wG1wxWdVlzkPraKGqdXivUNjHLoDHl+fX3w51LG72MviRS1rs/pqw40zTPyD3Gfnzl/ioDaqbeCN67/RIadXz3z4dmIRDIUVEw4RhN80XZgp41+B7t6N0WHWASyWzVOIStWVgR5XKs40O72bJMsZUz5z2DOrw==', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '221.6.15.218', '2018-03-19 17:29:35');
INSERT INTO `log_exception` VALUES ('54', '/User/Register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '221.6.15.218', '2018-03-19 17:29:46');
INSERT INTO `log_exception` VALUES ('55', '/User/Register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '221.6.15.218', '2018-03-19 17:29:55');
INSERT INTO `log_exception` VALUES ('56', '/User/Register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '221.6.15.218', '2018-03-19 17:30:03');
INSERT INTO `log_exception` VALUES ('57', '/User/ResetPwd', 'nsukey=eXhRydxRCt+WpFxx07MKzE0wcVoHvLzPfHkM+dsKsyAGrRbmlW/HRot85zajl5V9A/ypA2newckfQ/xLHnIBouBenxYNWA0U+le+ZXoFz0sJ8IkB0fvVgc7lcXI2WZ4bhVTyN8A82CBCq6QlS3MnrUD2hPZnRY36RDxarFHcVu3CMHlY1ItiiLjMfN6KHhl2LtNU6Q2MyufLxJEFIrxyiA==', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '61.151.178.171', '2018-03-19 17:30:28');
INSERT INTO `log_exception` VALUES ('58', '/User/Register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '101.226.33.203', '2018-03-19 17:30:33');
INSERT INTO `log_exception` VALUES ('59', '/User/Register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-19 17:30:59');
INSERT INTO `log_exception` VALUES ('60', '/User/Register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-19 17:31:23');
INSERT INTO `log_exception` VALUES ('61', '/User/register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-19 17:31:34');
INSERT INTO `log_exception` VALUES ('62', '/User/register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-19 17:36:34');
INSERT INTO `log_exception` VALUES ('63', '/User/register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-19 17:37:02');
INSERT INTO `log_exception` VALUES ('64', '/User/register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-19 17:37:05');
INSERT INTO `log_exception` VALUES ('65', '/User/register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-19 17:42:09');
INSERT INTO `log_exception` VALUES ('66', '/User/Register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-19 17:42:16');
INSERT INTO `log_exception` VALUES ('67', '/User/Register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-19 17:42:29');
INSERT INTO `log_exception` VALUES ('68', '/User/Register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-19 17:43:02');
INSERT INTO `log_exception` VALUES ('69', '/User/Register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-19 17:43:49');
INSERT INTO `log_exception` VALUES ('70', '/User/Register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-19 17:44:30');
INSERT INTO `log_exception` VALUES ('71', '/user/register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-19 17:44:51');
INSERT INTO `log_exception` VALUES ('72', '/User/ResetPwd', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-19 17:48:54');
INSERT INTO `log_exception` VALUES ('73', '/User/ResetPwd/', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-19 17:49:53');
INSERT INTO `log_exception` VALUES ('74', '/User/Register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-19 17:52:58');
INSERT INTO `log_exception` VALUES ('75', '/User/Register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-19 17:53:06');
INSERT INTO `log_exception` VALUES ('76', '/User/Register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-19 17:53:10');
INSERT INTO `log_exception` VALUES ('77', '/User/Register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-19 17:53:19');
INSERT INTO `log_exception` VALUES ('78', '/User/Register/', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-19 17:53:36');
INSERT INTO `log_exception` VALUES ('79', '/User/register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-19 17:57:40');
INSERT INTO `log_exception` VALUES ('80', '/User/register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-19 17:57:51');
INSERT INTO `log_exception` VALUES ('81', '/User/Register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-19 17:57:58');
INSERT INTO `log_exception` VALUES ('82', '/User/Register', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-19 18:10:29');
INSERT INTO `log_exception` VALUES ('83', '/User/ResetPwd', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-19 18:11:36');
INSERT INTO `log_exception` VALUES ('84', '/Company/New', '{\"Id\":\"0\",\"Name\":\"八集粮食收购门市\",\"Address\":\"泗阳县八集街\"}', 'An error occurred while updating the entries. See the inner exception for details.\nDuplicate entry \'2\' for key \'uq_userid\'\nDuplicate entry \'2\' for key \'uq_userid\'\n', '   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)\n   at Microsoft.EntityFrameworkCore.Update.Internal.MySqlBatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)\n   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)\n   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)\n   at GrainManage.Core.BaseUnitOfWork.SaveChanges(Boolean forceSave) in D:\\github.netcore.GrainManage\\Libraries\\GrainManage.Core\\BaseUnitOfWork.cs:line 125\n   at GrainManage.Core.Repository`1.Add(T item) in D:\\github.netcore.GrainManage\\Libraries\\GrainManage.Core\\Repository.cs:line 45\n   at GrainManage.Web.Controllers.CompanyController.New(CompanyDto input, IFormFile imgFile) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Controllers\\CompanyController.cs:line 92\n   at lambda_method(Closure , Object , Object[] )\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '153.3.138.60', '2018-03-19 21:20:58');
INSERT INTO `log_exception` VALUES ('85', '/Company/New', '{\"Id\":\"0\",\"Name\":\"八集粮食收购门市\",\"Address\":\"泗阳县八集街\"}', 'An error occurred while updating the entries. See the inner exception for details.\nDuplicate entry \'2\' for key \'uq_userid\'\nDuplicate entry \'2\' for key \'uq_userid\'\n', '   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)\n   at Microsoft.EntityFrameworkCore.Update.Internal.MySqlBatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)\n   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)\n   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)\n   at GrainManage.Core.BaseUnitOfWork.SaveChanges(Boolean forceSave) in D:\\github.netcore.GrainManage\\Libraries\\GrainManage.Core\\BaseUnitOfWork.cs:line 125\n   at GrainManage.Core.Repository`1.Add(T item) in D:\\github.netcore.GrainManage\\Libraries\\GrainManage.Core\\Repository.cs:line 45\n   at GrainManage.Web.Controllers.CompanyController.New(CompanyDto input, IFormFile imgFile) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Controllers\\CompanyController.cs:line 92\n   at lambda_method(Closure , Object , Object[] )\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '153.3.138.60', '2018-03-19 21:22:36');
INSERT INTO `log_exception` VALUES ('86', '/Address/RefreshCache', '', 'Sequence contains no elements\n', '   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)\n   at GrainManage.Web.LogActionAttribute.OnActionExecuted(ActionExecutedContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 43\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '153.3.138.60', '2018-03-19 22:16:12');
INSERT INTO `log_exception` VALUES ('87', '/task/BuildCompLogo', '', 'Could not find a part of the path \'/www/images/company/logo/fafa5efeaf3cbe3b23b2748d13e629a1.jpg\'.\n', '   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)\n   at SixLabors.ImageSharp.IO.LocalFileSystem.Create(String path)\n   at SixLabors.ImageSharp.ImageExtensions.Save[TPixel](Image`1 source, String filePath, IImageEncoder encoder)\n   at SixLabors.ImageSharp.ImageExtensions.Save[TPixel](Image`1 source, String filePath)\n   at GrainManage.Web.Common.ImageUtil.BuildCompLogo(String imgPath, String logoPath) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Common\\ImageUtil.cs:line 23\n   at GrainManage.Web.Controllers.TaskController.BuildCompLogo() in D:\\github.netcore.GrainManage\\GrainManage.Web\\Controllers\\TaskController.cs:line 145\n   at lambda_method(Closure , Object , Object[] )\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '221.6.15.218', '2018-03-20 11:22:04');
INSERT INTO `log_exception` VALUES ('88', '/task/BuildCompLogo', '', 'Could not find a part of the path \'/www/images/company/logo/fafa5efeaf3cbe3b23b2748d13e629a1.jpg\'.\n', '   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)\n   at SixLabors.ImageSharp.IO.LocalFileSystem.Create(String path)\n   at SixLabors.ImageSharp.ImageExtensions.Save[TPixel](Image`1 source, String filePath, IImageEncoder encoder)\n   at SixLabors.ImageSharp.ImageExtensions.Save[TPixel](Image`1 source, String filePath)\n   at GrainManage.Web.Common.ImageUtil.BuildCompLogo(String imgPath, String logoPath) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Common\\ImageUtil.cs:line 23\n   at GrainManage.Web.Controllers.TaskController.BuildCompLogo() in D:\\github.netcore.GrainManage\\GrainManage.Web\\Controllers\\TaskController.cs:line 145\n   at lambda_method(Closure , Object , Object[] )\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '221.6.15.218', '2018-03-20 11:22:13');
INSERT INTO `log_exception` VALUES ('89', '/Task/BuildCompLogo', '', 'Could not find a part of the path \'/www/images/company/logo/fafa5efeaf3cbe3b23b2748d13e629a1.jpg\'.\n', '   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)\n   at SixLabors.ImageSharp.IO.LocalFileSystem.Create(String path)\n   at SixLabors.ImageSharp.ImageExtensions.Save[TPixel](Image`1 source, String filePath, IImageEncoder encoder)\n   at SixLabors.ImageSharp.ImageExtensions.Save[TPixel](Image`1 source, String filePath)\n   at GrainManage.Web.Common.ImageUtil.BuildCompLogo(String imgPath, String logoPath) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Common\\ImageUtil.cs:line 23\n   at GrainManage.Web.Controllers.TaskController.BuildCompLogo() in D:\\github.netcore.GrainManage\\GrainManage.Web\\Controllers\\TaskController.cs:line 145\n   at lambda_method(Closure , Object , Object[] )\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '221.6.15.218', '2018-03-20 11:22:21');
INSERT INTO `log_exception` VALUES ('90', '/Task/BuildCompLogo', '', 'Could not find a part of the path \'/www/images/company/logo/fafa5efeaf3cbe3b23b2748d13e629a1.jpg\'.\n', '   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)\n   at SixLabors.ImageSharp.IO.LocalFileSystem.Create(String path)\n   at SixLabors.ImageSharp.ImageExtensions.Save[TPixel](Image`1 source, String filePath, IImageEncoder encoder)\n   at SixLabors.ImageSharp.ImageExtensions.Save[TPixel](Image`1 source, String filePath)\n   at GrainManage.Web.Common.ImageUtil.BuildCompLogo(String imgPath, String logoPath) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Common\\ImageUtil.cs:line 23\n   at GrainManage.Web.Controllers.TaskController.BuildCompLogo() in D:\\github.netcore.GrainManage\\GrainManage.Web\\Controllers\\TaskController.cs:line 145\n   at lambda_method(Closure , Object , Object[] )\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '221.6.15.218', '2018-03-20 11:24:41');
INSERT INTO `log_exception` VALUES ('91', '/Task/BuildCompLogo', '', 'Could not find a part of the path \'/www/images/company/logo/fafa5efeaf3cbe3b23b2748d13e629a1.jpg\'.\n', '   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)\n   at SixLabors.ImageSharp.IO.LocalFileSystem.Create(String path)\n   at SixLabors.ImageSharp.ImageExtensions.Save[TPixel](Image`1 source, String filePath, IImageEncoder encoder)\n   at SixLabors.ImageSharp.ImageExtensions.Save[TPixel](Image`1 source, String filePath)\n   at GrainManage.Web.Common.ImageUtil.BuildCompLogo(String imgPath, String logoPath) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Common\\ImageUtil.cs:line 23\n   at GrainManage.Web.Controllers.TaskController.BuildCompLogo() in D:\\github.netcore.GrainManage\\GrainManage.Web\\Controllers\\TaskController.cs:line 145\n   at lambda_method(Closure , Object , Object[] )\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '221.6.15.218', '2018-03-20 11:25:38');
INSERT INTO `log_exception` VALUES ('92', '/Task/BuildCompLogo', '', 'Could not find a part of the path \'/www/images/company/logo/fafa5efeaf3cbe3b23b2748d13e629a1.jpg\'.\n', '   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)\n   at SixLabors.ImageSharp.IO.LocalFileSystem.Create(String path)\n   at SixLabors.ImageSharp.ImageExtensions.Save[TPixel](Image`1 source, String filePath, IImageEncoder encoder)\n   at SixLabors.ImageSharp.ImageExtensions.Save[TPixel](Image`1 source, String filePath)\n   at GrainManage.Web.Common.ImageUtil.BuildCompLogo(String imgPath, String logoPath) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Common\\ImageUtil.cs:line 23\n   at GrainManage.Web.Controllers.TaskController.BuildCompLogo() in D:\\github.netcore.GrainManage\\GrainManage.Web\\Controllers\\TaskController.cs:line 145\n   at lambda_method(Closure , Object , Object[] )\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '221.6.15.218', '2018-03-20 11:32:39');
INSERT INTO `log_exception` VALUES ('93', '/Task/BuildCompLogo', '', 'Could not find a part of the path \'/www/images/company/logo/fafa5efeaf3cbe3b23b2748d13e629a1.jpg\'.\n', '   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)\n   at SixLabors.ImageSharp.IO.LocalFileSystem.Create(String path)\n   at SixLabors.ImageSharp.ImageExtensions.Save[TPixel](Image`1 source, String filePath, IImageEncoder encoder)\n   at SixLabors.ImageSharp.ImageExtensions.Save[TPixel](Image`1 source, String filePath)\n   at GrainManage.Web.Common.ImageUtil.BuildCompLogo(String imgPath, String logoPath) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Common\\ImageUtil.cs:line 23\n   at GrainManage.Web.Controllers.TaskController.BuildCompLogo() in D:\\github.netcore.GrainManage\\GrainManage.Web\\Controllers\\TaskController.cs:line 145\n   at lambda_method(Closure , Object , Object[] )\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-20 11:33:36');
INSERT INTO `log_exception` VALUES ('94', '/task/DeleteCompLogo', '', 'Could not find a part of the path \'/www/images/company/logo\'.\n', '   at System.IO.UnixFileSystem.FileSystemEnumerable`1.OpenDirectory(String fullPath)\n   at System.IO.UnixFileSystem.FileSystemEnumerable`1.Enumerate()\n   at System.IO.UnixFileSystem.FileSystemEnumerable`1..ctor(String userPath, String searchPattern, SearchOption searchOption, SearchTarget searchTarget, Func`3 translateResult)\n   at System.IO.UnixFileSystem.EnumeratePaths(String path, String searchPattern, SearchOption searchOption, SearchTarget searchTarget)\n   at System.IO.Directory.InternalGetFileDirectoryNames(String path, String userPathOriginal, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searchOption)\n   at System.IO.Directory.GetFiles(String path)\n   at GrainManage.Web.Controllers.TaskController.DeleteCompLogo() in D:\\github.netcore.GrainManage\\GrainManage.Web\\Controllers\\TaskController.cs:line 108\n   at lambda_method(Closure , Object , Object[] )\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-20 11:35:27');
INSERT INTO `log_exception` VALUES ('95', '/task/DeleteCompLogo', '', 'Could not find a part of the path \'/www/images/company/logo\'.\n', '   at System.IO.UnixFileSystem.FileSystemEnumerable`1.OpenDirectory(String fullPath)\n   at System.IO.UnixFileSystem.FileSystemEnumerable`1.Enumerate()\n   at System.IO.UnixFileSystem.FileSystemEnumerable`1..ctor(String userPath, String searchPattern, SearchOption searchOption, SearchTarget searchTarget, Func`3 translateResult)\n   at System.IO.UnixFileSystem.EnumeratePaths(String path, String searchPattern, SearchOption searchOption, SearchTarget searchTarget)\n   at System.IO.Directory.InternalGetFileDirectoryNames(String path, String userPathOriginal, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searchOption)\n   at System.IO.Directory.GetFiles(String path)\n   at GrainManage.Web.Controllers.TaskController.DeleteCompLogo() in D:\\github.netcore.GrainManage\\GrainManage.Web\\Controllers\\TaskController.cs:line 108\n   at lambda_method(Closure , Object , Object[] )\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '221.6.15.218', '2018-03-20 11:36:18');
INSERT INTO `log_exception` VALUES ('96', '/task/DeleteCompLogo', '', 'Could not find a part of the path \'/www/images/company/logo\'.\n', '   at System.IO.UnixFileSystem.FileSystemEnumerable`1.OpenDirectory(String fullPath)\n   at System.IO.UnixFileSystem.FileSystemEnumerable`1.Enumerate()\n   at System.IO.UnixFileSystem.FileSystemEnumerable`1..ctor(String userPath, String searchPattern, SearchOption searchOption, SearchTarget searchTarget, Func`3 translateResult)\n   at System.IO.UnixFileSystem.EnumeratePaths(String path, String searchPattern, SearchOption searchOption, SearchTarget searchTarget)\n   at System.IO.Directory.InternalGetFileDirectoryNames(String path, String userPathOriginal, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searchOption)\n   at System.IO.Directory.GetFiles(String path)\n   at GrainManage.Web.Controllers.TaskController.DeleteCompLogo() in D:\\github.netcore.GrainManage\\GrainManage.Web\\Controllers\\TaskController.cs:line 108\n   at lambda_method(Closure , Object , Object[] )\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '172.16.232.255', '2018-03-20 11:37:43');
INSERT INTO `log_exception` VALUES ('97', '/User/ForgetPwd', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '221.6.15.218', '2018-03-20 11:38:13');
INSERT INTO `log_exception` VALUES ('98', '/User/SignUp', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 27\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '221.6.15.218', '2018-03-20 11:38:18');
INSERT INTO `log_exception` VALUES ('99', '/Company/Edit', '{\"Id\":\"1\",\"Name\":\"粮食收购中心\",\"Address\":\"北京市中南海\"}', 'Could not find a part of the path \'/www/images/company/logo/9e6a6494c0ea13d6261b507b67ed411e.jpg\'.\n', '   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)\n   at SixLabors.ImageSharp.IO.LocalFileSystem.Create(String path)\n   at SixLabors.ImageSharp.ImageExtensions.Save[TPixel](Image`1 source, String filePath, IImageEncoder encoder)\n   at SixLabors.ImageSharp.ImageExtensions.Save[TPixel](Image`1 source, String filePath)\n   at GrainManage.Web.Common.ImageUtil.BuildCompLogo(String imgPath, String logoPath) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Common\\ImageUtil.cs:line 23\n   at GrainManage.Web.Controllers.CompanyController.Edit(CompanyDto input, IFormFile imgFile) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Controllers\\CompanyController.cs:line 146\n   at lambda_method(Closure , Object , Object[] )\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '221.6.15.218', '2018-03-20 11:40:09');
INSERT INTO `log_exception` VALUES ('100', '/Company/Edit', '{\"Id\":\"1\",\"Name\":\"粮食收购中心\",\"Address\":\"北京市中南海\"}', 'Could not find a part of the path \'/www/images/company/logo/fb77f99935b8c1cf47c68b5843943a1f.jpg\'.\n', '   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)\n   at SixLabors.ImageSharp.IO.LocalFileSystem.Create(String path)\n   at SixLabors.ImageSharp.ImageExtensions.Save[TPixel](Image`1 source, String filePath, IImageEncoder encoder)\n   at SixLabors.ImageSharp.ImageExtensions.Save[TPixel](Image`1 source, String filePath)\n   at GrainManage.Web.Common.ImageUtil.BuildCompLogo(String imgPath, String logoPath) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Common\\ImageUtil.cs:line 23\n   at GrainManage.Web.Controllers.CompanyController.Edit(CompanyDto input, IFormFile imgFile) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Controllers\\CompanyController.cs:line 146\n   at lambda_method(Closure , Object , Object[] )\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '221.6.15.218', '2018-03-20 11:40:50');
INSERT INTO `log_exception` VALUES ('101', '/User/SignIn', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 29\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '153.3.138.60', '2018-03-20 19:53:31');
INSERT INTO `log_exception` VALUES ('102', '/User/SignIn', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 29\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '153.3.138.60', '2018-03-20 19:53:38');
INSERT INTO `log_exception` VALUES ('103', '/User/SignIn', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 29\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '153.3.138.60', '2018-03-20 19:53:40');
INSERT INTO `log_exception` VALUES ('104', '/User/SignIn', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 29\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '153.3.138.60', '2018-03-20 19:53:45');
INSERT INTO `log_exception` VALUES ('105', '/User/SignIn', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 29\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '153.3.138.60', '2018-03-20 19:54:02');
INSERT INTO `log_exception` VALUES ('106', '/User/SignIn', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 29\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '153.3.138.60', '2018-03-20 19:54:05');
INSERT INTO `log_exception` VALUES ('107', '/User/SignIn', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 29\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '153.3.138.60', '2018-03-20 19:54:06');
INSERT INTO `log_exception` VALUES ('108', '/User/SignIn', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 29\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '153.3.138.60', '2018-03-20 19:54:07');
INSERT INTO `log_exception` VALUES ('109', '/User/SignIn', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 29\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '153.3.138.60', '2018-03-20 19:54:32');
INSERT INTO `log_exception` VALUES ('110', '/User/SignIn', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 29\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '153.3.138.60', '2018-03-20 19:57:14');
INSERT INTO `log_exception` VALUES ('111', '/User/SignIn', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 29\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '153.3.138.60', '2018-03-20 19:57:21');
INSERT INTO `log_exception` VALUES ('112', '/User/SignIn', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 29\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '153.3.138.60', '2018-03-20 20:04:47');
INSERT INTO `log_exception` VALUES ('113', '/User/SignIn', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 29\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '153.3.138.60', '2018-03-20 20:04:49');
INSERT INTO `log_exception` VALUES ('114', '/User/SignIn', '', 'Object reference not set to an instance of an object.\n', '   at GrainManage.Web.LogActionAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\\github.netcore.GrainManage\\GrainManage.Web\\Attribute\\LogActionAttribute.cs:line 29\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()', '221.6.15.218', '2018-03-20 20:05:26');

-- ----------------------------
-- Table structure for `log_job`
-- ----------------------------
DROP TABLE IF EXISTS `log_job`;
CREATE TABLE `log_job` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `JobName` varchar(20) NOT NULL COMMENT '任务名称',
  `Status` varchar(20) DEFAULT NULL COMMENT '状态',
  `Remark` varchar(600) DEFAULT NULL COMMENT '说明',
  `StartTime` datetime NOT NULL COMMENT '开始时间',
  `EndTime` datetime DEFAULT NULL COMMENT '结束时间',
  `TimeSpan` time DEFAULT NULL COMMENT '耗时',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of log_job
-- ----------------------------

-- ----------------------------
-- Table structure for `log_login`
-- ----------------------------
DROP TABLE IF EXISTS `log_login`;
CREATE TABLE `log_login` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `UserName` varchar(20) DEFAULT NULL COMMENT '用户名称',
  `LoginIP` varchar(64) DEFAULT NULL COMMENT '客户端登录IP',
  `Status` varchar(60) NOT NULL COMMENT '登录状态',
  `Level` smallint(6) NOT NULL COMMENT '级别-只有超过该级别的用户才可查看该条记录',
  `TypeId` smallint(6) NOT NULL DEFAULT '0' COMMENT '0：后台登录 1：微信端登录',
  `CreatedAt` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=221 DEFAULT CHARSET=utf8 COMMENT='后台登录日志';

-- ----------------------------
-- Records of log_login
-- ----------------------------
INSERT INTO `log_login` VALUES ('142', 'bijinshu', '221.6.15.218', '??', '100', '0', '2018-03-17 15:23:42');
INSERT INTO `log_login` VALUES ('143', 'bijinshu', '221.6.15.218', '??', '100', '0', '2018-03-17 15:24:57');
INSERT INTO `log_login` VALUES ('144', 'bijinshu', '122.96.42.158', '????,????????.', '0', '0', '2018-03-17 15:44:51');
INSERT INTO `log_login` VALUES ('145', 'bijinshu', '122.96.42.158', '??', '100', '0', '2018-03-17 15:45:05');
INSERT INTO `log_login` VALUES ('146', 'bijinshu', '221.6.15.218', '??', '100', '0', '2018-03-17 17:05:26');
INSERT INTO `log_login` VALUES ('147', 'bj', '180.174.190.213', '??', '90', '0', '2018-03-17 20:06:41');
INSERT INTO `log_login` VALUES ('148', 'bmx', '153.3.43.174', '??', '90', '0', '2018-03-17 20:06:58');
INSERT INTO `log_login` VALUES ('149', 'bj', '180.174.190.213', '??', '90', '0', '2018-03-17 20:09:10');
INSERT INTO `log_login` VALUES ('150', 'bj', '180.174.190.213', '??', '90', '0', '2018-03-17 20:10:29');
INSERT INTO `log_login` VALUES ('151', 'bj', '180.174.190.213', '??', '90', '0', '2018-03-17 20:12:23');
INSERT INTO `log_login` VALUES ('152', 'bj', '180.174.190.213', '??', '90', '0', '2018-03-17 20:16:46');
INSERT INTO `log_login` VALUES ('153', 'bj', '180.174.190.213', '??', '90', '0', '2018-03-17 20:16:56');
INSERT INTO `log_login` VALUES ('154', 'bj', '180.174.190.213', '好不好', '90', '0', '2018-03-17 20:17:05');
INSERT INTO `log_login` VALUES ('155', 'bj', '180.174.190.213', '??', '90', '0', '2018-03-17 20:17:26');
INSERT INTO `log_login` VALUES ('156', 'bmx', '153.3.43.174', '??', '90', '0', '2018-03-17 20:28:57');
INSERT INTO `log_login` VALUES ('157', 'bj', '180.174.190.213', '??', '90', '0', '2018-03-18 06:25:54');
INSERT INTO `log_login` VALUES ('158', 'bjc', '153.3.43.174', '??', '90', '0', '2018-03-18 11:09:11');
INSERT INTO `log_login` VALUES ('159', 'bi', '153.3.43.174', '??????.', '0', '0', '2018-03-18 11:27:44');
INSERT INTO `log_login` VALUES ('160', 'bmx', '153.3.43.174', '??', '90', '0', '2018-03-18 11:46:21');
INSERT INTO `log_login` VALUES ('161', 'bi', '192.168.111.88', '??????.', '0', '0', '2018-03-18 12:06:50');
INSERT INTO `log_login` VALUES ('162', 'bi', '192.168.111.88', '用户名不存在.', '0', '0', '2018-03-18 12:14:27');
INSERT INTO `log_login` VALUES ('163', 'bi', '192.168.111.88', '用户名不存在.', '0', '0', '2018-03-18 12:24:32');
INSERT INTO `log_login` VALUES ('164', 'bi', '192.168.111.88', '用户名不存在.', '0', '0', '2018-03-18 12:25:11');
INSERT INTO `log_login` VALUES ('165', 'bmx', '192.168.111.88', '成功', '90', '0', '2018-03-18 12:25:32');
INSERT INTO `log_login` VALUES ('166', 'bijinshu', '112.80.124.139', '成功', '100', '0', '2018-03-18 13:45:16');
INSERT INTO `log_login` VALUES ('167', 'bmx', '112.86.175.108', '成功', '90', '0', '2018-03-18 20:18:25');
INSERT INTO `log_login` VALUES ('168', 'bjc', '180.174.190.213', '成功', '90', '0', '2018-03-19 10:22:56');
INSERT INTO `log_login` VALUES ('169', 'bijinshu', '221.6.15.218', '登录失败,用户名或密码错误.', '0', '0', '2018-03-19 14:49:58');
INSERT INTO `log_login` VALUES ('170', 'bijinshu', '172.16.232.255', '登录失败,用户名或密码错误.', '0', '0', '2018-03-19 14:56:26');
INSERT INTO `log_login` VALUES ('171', 'bijinshu', '221.6.15.218', '成功', '100', '0', '2018-03-19 15:03:59');
INSERT INTO `log_login` VALUES ('172', 'bmx', '221.6.15.218', '成功', '80', '0', '2018-03-19 15:08:29');
INSERT INTO `log_login` VALUES ('173', 'bmx', '221.6.15.218', '成功', '80', '0', '2018-03-19 15:12:59');
INSERT INTO `log_login` VALUES ('174', 'bmx', '221.6.15.218', '成功', '80', '0', '2018-03-19 16:07:15');
INSERT INTO `log_login` VALUES ('175', 'bijinshu', '221.6.15.218', '成功', '100', '0', '2018-03-19 17:17:38');
INSERT INTO `log_login` VALUES ('176', 'bjc', '221.6.15.218', '成功', '90', '0', '2018-03-19 17:19:51');
INSERT INTO `log_login` VALUES ('177', 'bijinshu', '221.6.15.218', '成功', '100', '0', '2018-03-19 17:21:50');
INSERT INTO `log_login` VALUES ('178', 'bjc', '221.6.15.218', '成功', '80', '0', '2018-03-19 17:24:20');
INSERT INTO `log_login` VALUES ('179', 'bijinshu', '153.3.138.60', '成功', '100', '0', '2018-03-19 20:32:47');
INSERT INTO `log_login` VALUES ('180', 'bjc', '153.3.138.60', '登录失败,用户名或密码错误.', '0', '0', '2018-03-19 21:09:59');
INSERT INTO `log_login` VALUES ('181', 'bjc', '153.3.138.60', '成功', '80', '0', '2018-03-19 21:10:05');
INSERT INTO `log_login` VALUES ('182', 'bj', '117.136.8.78', '成功', '80', '0', '2018-03-19 21:11:05');
INSERT INTO `log_login` VALUES ('183', 'bj', '117.136.8.78', '成功', '80', '0', '2018-03-19 21:13:24');
INSERT INTO `log_login` VALUES ('184', 'bj', '117.136.8.78', '成功', '80', '0', '2018-03-19 21:13:51');
INSERT INTO `log_login` VALUES ('185', 'bijinshu', '153.3.138.60', '登录失败,用户名或密码错误.', '0', '0', '2018-03-19 21:43:19');
INSERT INTO `log_login` VALUES ('186', 'bijinshu', '153.3.138.60', '成功', '100', '0', '2018-03-19 21:43:28');
INSERT INTO `log_login` VALUES ('187', 'test', '153.3.138.60', '登录失败,该账户被禁用.', '0', '0', '2018-03-19 21:47:13');
INSERT INTO `log_login` VALUES ('188', 'test', '153.3.138.60', '成功', '80', '0', '2018-03-19 21:52:15');
INSERT INTO `log_login` VALUES ('189', 'test', '153.3.138.60', '成功', '80', '0', '2018-03-19 21:54:37');
INSERT INTO `log_login` VALUES ('190', 'bijinshu', '153.3.138.60', '成功', '100', '0', '2018-03-19 22:02:59');
INSERT INTO `log_login` VALUES ('191', 'bijinshu', '221.6.15.218', '成功', '100', '0', '2018-03-20 11:38:43');
INSERT INTO `log_login` VALUES ('192', 'bijinshu', '47.97.192.196', '登录失败,用户名或密码错误.', '0', '0', '2018-03-20 15:38:45');
INSERT INTO `log_login` VALUES ('193', 'bijinshu', '47.97.192.196', '成功', '100', '0', '2018-03-20 15:38:53');
INSERT INTO `log_login` VALUES ('194', 'bijinshu', '153.3.138.60', '成功', '100', '0', '2018-03-20 20:15:40');
INSERT INTO `log_login` VALUES ('195', 'bijinshu', '221.6.15.218', '成功', '100', '0', '2018-03-21 12:00:37');
INSERT INTO `log_login` VALUES ('196', 'bijinshu', '221.6.15.218', '成功', '100', '0', '2018-03-21 17:30:15');
INSERT INTO `log_login` VALUES ('197', 'bijinshu', '221.6.15.218', '登录失败,用户名或密码错误.', '0', '0', '2018-03-22 09:56:28');
INSERT INTO `log_login` VALUES ('198', 'bijinshu', '221.6.15.218', '成功', '100', '0', '2018-03-22 09:56:38');
INSERT INTO `log_login` VALUES ('199', 'bj', '183.193.144.3', '成功', '80', '0', '2018-03-22 14:16:53');
INSERT INTO `log_login` VALUES ('200', 'bjc', '122.96.40.229', '成功', '80', '0', '2018-03-22 14:21:59');
INSERT INTO `log_login` VALUES ('201', 'bjc', 'localhost', '成功', '80', '0', '2018-03-22 16:28:04');
INSERT INTO `log_login` VALUES ('202', 'bjc', 'localhost', '成功', '80', '0', '2018-03-22 16:28:51');
INSERT INTO `log_login` VALUES ('203', 'bjc', 'localhost', '成功', '80', '0', '2018-03-22 16:29:07');
INSERT INTO `log_login` VALUES ('204', 'bjc', 'localhost', '成功', '80', '0', '2018-03-22 16:30:07');
INSERT INTO `log_login` VALUES ('205', 'bjc', 'localhost', '成功', '80', '0', '2018-03-22 16:30:49');
INSERT INTO `log_login` VALUES ('206', 'bjc', 'localhost', '成功', '80', '0', '2018-03-22 16:38:52');
INSERT INTO `log_login` VALUES ('207', 'bjc', 'localhost', '成功', '80', '0', '2018-03-22 16:39:07');
INSERT INTO `log_login` VALUES ('208', 'bjc', 'localhost', '成功', '80', '0', '2018-03-22 16:45:23');
INSERT INTO `log_login` VALUES ('209', 'bjc', 'localhost', '成功', '80', '0', '2018-03-22 16:45:53');
INSERT INTO `log_login` VALUES ('210', 'bjc', 'localhost', '成功', '80', '0', '2018-03-22 16:46:01');
INSERT INTO `log_login` VALUES ('211', 'bjc', 'localhost', '成功', '80', '0', '2018-03-22 16:46:09');
INSERT INTO `log_login` VALUES ('212', 'bjc', 'localhost', '成功', '80', '0', '2018-03-22 16:46:15');
INSERT INTO `log_login` VALUES ('213', 'bjc', 'localhost', '成功', '80', '0', '2018-03-22 16:49:18');
INSERT INTO `log_login` VALUES ('214', 'bjc', 'localhost', '成功', '80', '0', '2018-03-22 16:49:45');
INSERT INTO `log_login` VALUES ('215', 'bjc', 'localhost', '成功', '80', '0', '2018-03-22 16:55:04');
INSERT INTO `log_login` VALUES ('216', 'bjc', 'localhost', '成功', '80', '0', '2018-03-22 16:55:24');
INSERT INTO `log_login` VALUES ('217', 'bjc', 'localhost', '成功', '80', '0', '2018-03-22 17:15:31');
INSERT INTO `log_login` VALUES ('218', 'bijinshu', 'localhost', '登录失败,用户名或密码错误.', '0', '0', '2018-03-23 14:50:04');
INSERT INTO `log_login` VALUES ('219', 'bijinshu', 'localhost', '成功', '100', '0', '2018-03-23 14:50:14');
INSERT INTO `log_login` VALUES ('220', 'bijinshu', 'localhost', '成功', '100', '0', '2018-03-23 17:23:41');

-- ----------------------------
-- Table structure for `rm_address`
-- ----------------------------
DROP TABLE IF EXISTS `rm_address`;
CREATE TABLE `rm_address` (
  `Path` varchar(255) NOT NULL DEFAULT '' COMMENT '接口路径',
  `IsWatching` tinyint(6) NOT NULL COMMENT '0:不监控 1:监控 ',
  `IsValid` tinyint(6) NOT NULL COMMENT '0:无效地址 1:有效地址',
  `TypeId` smallint(6) NOT NULL COMMENT '0:受保护 1:免权限验证',
  `Remark` varchar(200) NOT NULL DEFAULT '' COMMENT '说明',
  `CreatedAt` datetime NOT NULL COMMENT '创建时间',
  `ModifiedAt` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`Path`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='地址监控配置表';

-- ----------------------------
-- Records of rm_address
-- ----------------------------
INSERT INTO `rm_address` VALUES ('/Address/Edit', '1', '1', '0', '', '2018-03-16 20:20:12', '2018-03-19 22:09:47');
INSERT INTO `rm_address` VALUES ('/Address/Index', '0', '1', '0', '', '2018-03-16 20:20:12', null);
INSERT INTO `rm_address` VALUES ('/Address/Refresh', '0', '0', '0', '', '2018-03-16 20:20:12', '2018-03-16 20:35:35');
INSERT INTO `rm_address` VALUES ('/Address/RefreshCache', '1', '1', '0', '', '2018-03-16 20:35:35', '2018-03-19 22:15:54');
INSERT INTO `rm_address` VALUES ('/Address/RefreshDb', '1', '1', '0', '', '2018-03-16 20:35:35', '2018-03-19 22:15:45');
INSERT INTO `rm_address` VALUES ('/Company/DeleteFile', '1', '1', '1', '删除店铺图片', '2018-03-09 17:37:16', '2018-03-19 22:08:28');
INSERT INTO `rm_address` VALUES ('/Company/Edit', '1', '1', '0', '编辑店铺信息', '2018-03-09 17:37:16', '2018-03-19 22:05:17');
INSERT INTO `rm_address` VALUES ('/Company/GetList', '0', '1', '1', '在店铺管理员注册好店铺信息并添加好产品信息后，此接口获取店铺信息并展示给普通用户', '2018-03-09 17:37:16', '2018-03-19 22:08:08');
INSERT INTO `rm_address` VALUES ('/Company/New', '1', '1', '1', '店铺管理员首次登录时，会创建一个店铺', '2018-03-09 17:37:16', '2018-03-19 22:05:05');
INSERT INTO `rm_address` VALUES ('/Contact/Delete', '1', '1', '0', '', '2018-02-11 16:43:27', null);
INSERT INTO `rm_address` VALUES ('/Contact/Edit', '1', '1', '0', '', '2018-02-11 16:43:27', null);
INSERT INTO `rm_address` VALUES ('/Contact/GetList', '0', '1', '1', '', '2018-03-09 17:37:16', null);
INSERT INTO `rm_address` VALUES ('/Contact/Index', '0', '1', '0', '', '2018-02-11 16:43:27', null);
INSERT INTO `rm_address` VALUES ('/Contact/New', '1', '1', '0', '', '2018-02-11 16:43:27', null);
INSERT INTO `rm_address` VALUES ('/Employee/Delete', '1', '1', '0', '删除店员', '2018-03-09 17:37:16', '2018-03-19 22:12:28');
INSERT INTO `rm_address` VALUES ('/Employee/Edit', '1', '1', '0', '', '2018-03-09 17:37:16', '2018-03-19 22:11:52');
INSERT INTO `rm_address` VALUES ('/Employee/Index', '0', '1', '0', '', '2018-03-09 17:37:16', null);
INSERT INTO `rm_address` VALUES ('/Employee/New', '1', '1', '0', '', '2018-03-09 17:37:16', '2018-03-19 22:11:32');
INSERT INTO `rm_address` VALUES ('/Home/Index', '0', '1', '1', '', '2018-02-11 16:43:23', null);
INSERT INTO `rm_address` VALUES ('/Home/MenuTree', '0', '1', '1', '', '2018-03-09 17:37:16', null);
INSERT INTO `rm_address` VALUES ('/Log/ActionList', '0', '1', '0', '', '2018-03-09 17:37:16', null);
INSERT INTO `rm_address` VALUES ('/Log/DeleteException', '1', '1', '0', '删除异常', '2018-03-09 17:37:16', '2018-03-19 22:12:42');
INSERT INTO `rm_address` VALUES ('/Log/ExceptionList', '0', '1', '0', '', '2018-03-09 17:37:16', null);
INSERT INTO `rm_address` VALUES ('/Log/JobList', '0', '1', '0', '', '2018-03-09 17:37:16', null);
INSERT INTO `rm_address` VALUES ('/Log/LoginList', '0', '1', '0', '', '2018-03-09 17:37:16', null);
INSERT INTO `rm_address` VALUES ('/Order/ChangeStatus', '1', '1', '0', '', '2018-03-16 20:20:12', '2018-03-19 22:10:09');
INSERT INTO `rm_address` VALUES ('/Order/Detail', '0', '1', '0', '', '2018-03-16 20:20:12', null);
INSERT INTO `rm_address` VALUES ('/Order/Edit', '1', '1', '0', '', '2018-03-16 20:20:12', '2018-03-19 22:09:40');
INSERT INTO `rm_address` VALUES ('/Order/GetPersonalOrder', '0', '1', '1', '', '2018-03-16 20:20:12', null);
INSERT INTO `rm_address` VALUES ('/Order/Index', '0', '1', '0', '', '2018-03-16 20:20:12', null);
INSERT INTO `rm_address` VALUES ('/Order/New', '1', '1', '1', '普通用户在商铺页面下单', '2018-03-16 20:20:12', '2018-03-19 22:11:01');
INSERT INTO `rm_address` VALUES ('/Product/Copy', '1', '1', '1', '', '2018-03-09 17:37:16', '2018-03-19 22:11:40');
INSERT INTO `rm_address` VALUES ('/Product/Delete', '1', '1', '0', '删除产品', '2018-03-09 17:37:16', '2018-03-19 22:12:13');
INSERT INTO `rm_address` VALUES ('/Product/Edit', '1', '1', '0', '', '2018-03-09 17:37:16', '2018-03-19 22:11:43');
INSERT INTO `rm_address` VALUES ('/Product/Index', '0', '1', '0', '', '2018-03-09 17:37:16', null);
INSERT INTO `rm_address` VALUES ('/Product/List', '0', '1', '1', '', '2018-03-09 17:37:16', null);
INSERT INTO `rm_address` VALUES ('/Product/New', '1', '1', '0', '', '2018-03-09 17:37:16', '2018-03-19 22:11:26');
INSERT INTO `rm_address` VALUES ('/Role/Delete', '1', '1', '0', '', '2018-02-11 16:43:27', null);
INSERT INTO `rm_address` VALUES ('/Role/Edit', '1', '1', '0', '', '2018-02-11 16:43:27', null);
INSERT INTO `rm_address` VALUES ('/Role/GetRoleList', '0', '1', '1', '', '2018-03-09 17:37:16', null);
INSERT INTO `rm_address` VALUES ('/Role/Index', '0', '1', '0', '', '2018-02-11 16:43:27', null);
INSERT INTO `rm_address` VALUES ('/Role/New', '1', '1', '0', '', '2018-02-11 16:43:27', null);
INSERT INTO `rm_address` VALUES ('/Trade/Delete', '1', '1', '0', '', '2018-03-09 17:37:16', '2018-03-19 22:11:48');
INSERT INTO `rm_address` VALUES ('/Trade/Edit', '1', '1', '0', '', '2018-03-09 17:37:16', '2018-03-19 22:11:18');
INSERT INTO `rm_address` VALUES ('/Trade/GetByContactId', '1', '1', '0', '获取某个客户的交易历史', '2018-03-09 17:37:16', '2018-03-20 15:41:07');
INSERT INTO `rm_address` VALUES ('/Trade/Index', '0', '1', '0', '', '2018-03-09 17:37:16', null);
INSERT INTO `rm_address` VALUES ('/Trade/New', '1', '1', '0', '创建新订单（既可以在我的客户页面调用，也可以在交易管理页面调用）', '2018-03-09 17:37:16', '2018-03-19 22:11:13');
INSERT INTO `rm_address` VALUES ('/User/ChangePwd', '1', '1', '1', '', '2018-02-11 16:43:27', null);
INSERT INTO `rm_address` VALUES ('/User/Delete', '1', '1', '0', '', '2018-02-11 16:43:27', null);
INSERT INTO `rm_address` VALUES ('/User/Edit', '1', '1', '0', '', '2018-02-11 16:43:27', null);
INSERT INTO `rm_address` VALUES ('/User/ForgetPwd', '1', '1', '0', '重置密码', '2018-03-19 22:14:39', '2018-03-19 22:15:35');
INSERT INTO `rm_address` VALUES ('/User/Index', '0', '1', '0', '', '2018-02-11 16:43:27', null);
INSERT INTO `rm_address` VALUES ('/User/Info', '0', '1', '1', '', '2018-02-11 16:43:27', null);
INSERT INTO `rm_address` VALUES ('/User/New', '1', '1', '0', '后台创建新用户', '2018-02-11 16:43:27', '2018-03-19 22:13:50');
INSERT INTO `rm_address` VALUES ('/User/Register', '1', '0', '0', '', '2018-02-11 16:43:27', '2018-03-19 22:14:39');
INSERT INTO `rm_address` VALUES ('/User/ResetPwd', '1', '0', '0', '', '2018-02-11 16:43:27', '2018-03-19 22:14:39');
INSERT INTO `rm_address` VALUES ('/User/SelfInfo', '0', '1', '1', '', '2018-03-21 18:05:19', null);
INSERT INTO `rm_address` VALUES ('/User/SignIn', '0', '1', '0', '', '2018-02-11 16:43:27', '2018-03-22 10:11:33');
INSERT INTO `rm_address` VALUES ('/User/SignOut', '1', '1', '1', '', '2018-02-11 16:43:27', null);
INSERT INTO `rm_address` VALUES ('/User/SignUp', '1', '1', '0', '新用户注册', '2018-03-19 22:14:39', '2018-03-20 20:16:49');
INSERT INTO `rm_address` VALUES ('/User/SimpleInfo', '0', '1', '1', '', '2018-03-16 20:20:12', null);
INSERT INTO `rm_address` VALUES ('/User/UpdateSelf', '0', '1', '1', '', '2018-03-21 18:05:19', null);
INSERT INTO `rm_address` VALUES ('/WhiteIp/Delete', '1', '1', '0', '', '2018-03-20 20:17:06', '2018-03-20 20:17:41');
INSERT INTO `rm_address` VALUES ('/WhiteIp/Edit', '1', '1', '0', '', '2018-03-20 20:17:06', '2018-03-20 20:17:34');
INSERT INTO `rm_address` VALUES ('/WhiteIp/Index', '0', '1', '0', '', '2018-03-20 20:17:06', null);
INSERT INTO `rm_address` VALUES ('/WhiteIp/New', '1', '1', '0', '', '2018-03-20 20:17:06', '2018-03-20 20:17:30');

-- ----------------------------
-- Table structure for `rm_role`
-- ----------------------------
DROP TABLE IF EXISTS `rm_role`;
CREATE TABLE `rm_role` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(20) NOT NULL COMMENT '角色名称',
  `Auths` varchar(1600) NOT NULL DEFAULT '' COMMENT '权限列表',
  `Level` smallint(6) NOT NULL COMMENT '级别',
  `Remark` varchar(600) NOT NULL DEFAULT '' COMMENT '备注',
  `CreatedAt` datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COMMENT='系统角色，每个子系统都应该建立一个对应角色';

-- ----------------------------
-- Records of rm_role
-- ----------------------------
INSERT INTO `rm_role` VALUES ('1', '超级管理员', '', '100', '开发者专用用户', '2016-03-05 18:09:24');
INSERT INTO `rm_role` VALUES ('2', '普通用户', '', '80', '普通注册用户或关注公众号的用户', '2016-03-05 18:09:47');
INSERT INTO `rm_role` VALUES ('3', '店铺管理员', 'contact,contact.add,contact.delete,contact.edit,contact.trade,contact.view,employee,employee.add,employee.delete,employee.edit,employee.view,home,home.edit,order,order.add,order.approve,order.delete,order.detail,order.edit,order.view,product,product.add,product.copy,product.delete,product.edit,product.view,trade,trade.add,trade.delete,trade.edit,trade.view', '80', '管理店铺下的员工', '2017-07-19 18:27:34');
INSERT INTO `rm_role` VALUES ('4', '系统管理员', 'contact,contact.add,contact.delete,contact.edit,contact.trade,contact.view,employee,employee.add,employee.delete,employee.edit,employee.view,home,home.edit,log,log.action,log.action.view,log.exception,log.exception.delete,log.exception.view,log.job,log.job.view,log.login,log.login.view,order,order.add,order.approve,order.delete,order.detail,order.edit,order.view,product,product.add,product.copy,product.delete,product.edit,product.view,system,system.address,system.address.add,system.address.delete,system.address.edit,system.address.view,system.role,system.role.add,system.role.delete,system.role.edit,system.role.view,system.user,system.user.add,system.user.delete,system.user.edit,system.user.view,trade,trade.add,trade.delete,trade.edit,trade.view', '90', '管理系统用户', '2017-08-29 15:07:11');
INSERT INTO `rm_role` VALUES ('5', '店铺员工', 'contact,contact.add,contact.delete,contact.edit,contact.trade,contact.view,order,order.add,order.approve,order.detail,order.edit,order.view,product,product.add,product.copy,product.delete,product.edit,product.view,trade,trade.add,trade.delete,trade.edit,trade.view', '30', '店铺的员工，协助店铺管理员工作', '2018-02-26 11:31:05');

-- ----------------------------
-- Table structure for `rm_user`
-- ----------------------------
DROP TABLE IF EXISTS `rm_user`;
CREATE TABLE `rm_user` (
  `Id` int(32) NOT NULL AUTO_INCREMENT COMMENT '全局唯一编号',
  `UserName` varchar(20) NOT NULL DEFAULT '' COMMENT '用户名称、登录名称',
  `CompId` int(11) NOT NULL COMMENT '公司编号(-1:店铺管理员 需要完善店铺信息 0:普通用户)',
  `Pwd` varchar(42) NOT NULL DEFAULT '' COMMENT '密码',
  `Gender` smallint(6) NOT NULL DEFAULT '0' COMMENT '0:男 1:女',
  `Status` smallint(6) NOT NULL DEFAULT '0' COMMENT '0:禁用 1:启用',
  `RealName` varchar(20) NOT NULL DEFAULT '' COMMENT '真实姓名',
  `Mobile` char(11) NOT NULL DEFAULT '' COMMENT '手机号码',
  `Email` varchar(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  `QQ` varchar(20) NOT NULL DEFAULT '' COMMENT 'QQ',
  `Weixin` varchar(20) NOT NULL DEFAULT '' COMMENT '微信',
  `Address` varchar(60) NOT NULL DEFAULT '' COMMENT '住址',
  `Roles` varchar(200) NOT NULL DEFAULT '' COMMENT '角色',
  `Remark` varchar(200) NOT NULL DEFAULT '' COMMENT '备注',
  `CreatedAt` datetime NOT NULL COMMENT '创建时间',
  `CreatedBy` int(11) NOT NULL COMMENT '创建者： -1:系统注册 >0 表内其它用户',
  `ModifiedAt` datetime DEFAULT NULL COMMENT '上次活动时间',
  PRIMARY KEY (`Id`),
  KEY `uq_user_name` (`UserName`) USING BTREE,
  KEY `index_mobile` (`Mobile`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8 COMMENT='用户表';

-- ----------------------------
-- Records of rm_user
-- ----------------------------
INSERT INTO `rm_user` VALUES ('1', 'bijinshu', '1', 'a29f84d58cbbeae202d94673880d55d8ada19257', '0', '1', '毕金书', '15801992799', '914023961@qq.com', '914023961', 'bijinshu', '八集', '1', 'bijinshu', '2016-01-05 18:44:49', '0', '2018-03-22 16:20:07');
INSERT INTO `rm_user` VALUES ('2', 'bjc', '9', '69c5fcebaa65b560eaf06c3fbeb481ae44b8d618', '0', '1', '毕建昌', '15801992799', 'bijinshu@163.com', '12863589', 'bijinshu', '', '3', '555', '2016-01-05 18:44:49', '1', '2018-03-22 16:56:19');
INSERT INTO `rm_user` VALUES ('3', 'bj', '-1', '69c5fcebaa65b560eaf06c3fbeb481ae44b8d618', '1', '1', '毕娟', '15801992799', 'bijinshu@163.com', '96584258', '', '', '3', 'testroot', '2016-01-05 18:44:49', '1', '2018-03-19 15:08:05');
INSERT INTO `rm_user` VALUES ('15', 'bmx', '-1', '69c5fcebaa65b560eaf06c3fbeb481ae44b8d618', '0', '1', '毕明星', '15657476162', 'sdfd@xon.com', '95481563', 'bijinshusdlf', '', '3', '', '2018-03-02 10:12:34', '1', '2018-03-19 17:23:36');
INSERT INTO `rm_user` VALUES ('19', 'test', '10', '69c5fcebaa65b560eaf06c3fbeb481ae44b8d618', '0', '1', '', '15698751752', '', '', '', '', '3', '', '2018-03-19 21:47:08', '-1', '2018-03-21 17:40:47');
INSERT INTO `rm_user` VALUES ('20', 'bb', '0', '69c5fcebaa65b560eaf06c3fbeb481ae44b8d618', '0', '1', '', '15845751298', '', '', '', '', '2', '', '2018-03-23 10:12:08', '-1', '2018-03-23 10:12:08');

-- ----------------------------
-- Table structure for `rm_white_ip`
-- ----------------------------
DROP TABLE IF EXISTS `rm_white_ip`;
CREATE TABLE `rm_white_ip` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `IP` varchar(16) NOT NULL DEFAULT '' COMMENT 'IP',
  `Status` smallint(6) NOT NULL COMMENT '0：禁用 1：启用',
  `Remark` varchar(255) NOT NULL DEFAULT '' COMMENT '说明',
  `CreatedAt` datetime NOT NULL COMMENT '创建时间',
  `ModifiedAt` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COMMENT='ip白名单';

-- ----------------------------
-- Records of rm_white_ip
-- ----------------------------
INSERT INTO `rm_white_ip` VALUES ('1', '10.10.133.108', '1', '', '2018-02-11 16:42:31', null);
INSERT INTO `rm_white_ip` VALUES ('2', '221.6.15.218', '1', '', '2018-03-20 11:25:02', null);
INSERT INTO `rm_white_ip` VALUES ('3', '172.16.232.255', '1', '', '2018-03-20 11:36:29', null);
